spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:hogwartsdb
    username: dumbledore
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

hogwarts:
  registration:
    client:
      house:
        key: https://api-harrypotter.herokuapp.com/sortinghat
        info: https://api-harrypotter.herokuapp.com/house/{houseKey}